---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define memcached_user.
  set_fact:
    memcached_user: "{{ __memcached_user }}"
  when: memcached_user is not defined

# Setup/install tasks.
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Install Memcached.
  package: name=memcached state=installed
  register: memcached_install

# Configure Memcached.
- name: Copy Memcached configuration.
  template:
    src: memcached-{{ ansible_os_family }}.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart memcached

- name: Copy ench systemd unit for Debian
  template:
    src: memcached-{{ ansible_os_family }}-systemd.service.j2
    dest: "/lib/systemd/system/memcached.service"
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: Logfile exists
  file:
    path: "{{ memcached_log_file }}"
    state: present
    owner: syslog
    group: adm

- name: Copy ench rsyslog def for Debian
  template:
    src: memcached-{{ ansible_os_family }}-rsyslog.conf.j2
    dest: "/etc/rsyslog.d/20-memcached.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload rsyslog

- name: Copy ench logrotate def for Debian
  template:
    src: memcached-{{ ansible_os_family }}-logrotate.conf.j2
    dest: "/etc/logrotate.d/memcached"
    owner: root
    group: root
    mode: 0644

- name: Ensure Memcached is started and set to run on startup.
  service: name=memcached state=started enabled=yes
